const allowedStyles = {
  'align-content': [/^((?!url)[\d\w\s(),])*$/],
  'align-items': [/^((?!url)[\d\w\s(),])*$/],
  'align-self': [/^((?!url)[\d\w\s(),])*$/],
  animation: [/^((?!url)[\d\w\s(),])*$/],
  'animation-delay': [/^((?!url)[\d\w\s(),])*$/],
  'animation-direction': [/^((?!url)[\d\w\s(),])*$/],
  'animation-duration': [/^((?!url)[\d\w\s(),])*$/],
  'animation-fill-mode': [/^((?!url)[\d\w\s(),])*$/],
  'animation-iteration-count': [/^((?!url)[\d\w\s(),])*$/],
  'animation-name': [/^((?!url)[\d\w\s(),])*$/],
  'animation-play-state': [/^((?!url)[\d\w\s(),])*$/],
  'animation-timing-function': [/^((?!url)[\d\w\s(),])*$/],
  'backface-visibility': [/^((?!url)[\d\w\s(),])*$/],
  // background: [/^((?!url)[\d\w\s(),])*$/],
  // 'background-attachment': [/^((?!url)[\d\w\s(),])*$/],
  // 'background-clip': [/^((?!url)[\d\w\s(),])*$/],
  'background-color': [/^((?!url)[\d\w\s(),])*$/],
  // 'background-image': [/^((?!url)[\d\w\s(),])*$/],
  // 'background-origin': [/^((?!url)[\d\w\s(),])*$/],
  'background-position': [/^((?!url)[\d\w\s(),])*$/],
  'background-repeat': [/^((?!url)[\d\w\s(),])*$/],
  'background-size': [/^((?!url)[\d\w\s(),])*$/],
  border: [/^((?!url)[\d\w\s(),])*$/],
  'border-bottom': [/^((?!url)[\d\w\s(),])*$/],
  'border-bottom-color': [/^((?!url)[\d\w\s(),])*$/],
  'border-bottom-left-radius': [/^((?!url)[\d\w\s(),])*$/],
  'border-bottom-right-radius': [/^((?!url)[\d\w\s(),])*$/],
  'border-bottom-style': [/^((?!url)[\d\w\s(),])*$/],
  'border-bottom-width': [/^((?!url)[\d\w\s(),])*$/],
  'border-collapse': [/^((?!url)[\d\w\s(),])*$/],
  'border-color': [/^((?!url)[\d\w\s(),])*$/],
  'border-image': [/^((?!url)[\d\w\s(),])*$/],
  'border-image-outset': [/^((?!url)[\d\w\s(),])*$/],
  'border-image-repeat': [/^((?!url)[\d\w\s(),])*$/],
  'border-image-slice': [/^((?!url)[\d\w\s(),])*$/],
  'border-image-source': [/^((?!url)[\d\w\s(),])*$/],
  'border-image-width': [/^((?!url)[\d\w\s(),])*$/],
  'border-left': [/^((?!url)[\d\w\s(),])*$/],
  'border-left-color': [/^((?!url)[\d\w\s(),])*$/],
  'border-left-style': [/^((?!url)[\d\w\s(),])*$/],
  'border-left-width': [/^((?!url)[\d\w\s(),])*$/],
  'border-radius': [/^((?!url)[\d\w\s(),])*$/],
  'border-right': [/^((?!url)[\d\w\s(),])*$/],
  'border-right-color': [/^((?!url)[\d\w\s(),])*$/],
  'border-right-style': [/^((?!url)[\d\w\s(),])*$/],
  'border-right-width': [/^((?!url)[\d\w\s(),])*$/],
  'border-spacing': [/^((?!url)[\d\w\s(),])*$/],
  'border-style': [/^((?!url)[\d\w\s(),])*$/],
  'border-top': [/^((?!url)[\d\w\s(),])*$/],
  'border-top-color': [/^((?!url)[\d\w\s(),])*$/],
  'border-top-left-radius': [/^((?!url)[\d\w\s(),])*$/],
  'border-top-right-radius': [/^((?!url)[\d\w\s(),])*$/],
  'border-top-style': [/^((?!url)[\d\w\s(),])*$/],
  'border-top-width': [/^((?!url)[\d\w\s(),])*$/],
  'border-width': [/^((?!url)[\d\w\s(),])*$/],
  bottom: [/^((?!url)[\d\w\s(),])*$/],
  'box-shadow': [/^((?!url)[\d\w\s(),])*$/],
  'box-sizing': [/^((?!url)[\d\w\s(),])*$/],
  'caption-side': [/^((?!url)[\d\w\s(),])*$/],
  clear: [/^((?!url)[\d\w\s(),])*$/],
  clip: [/^((?!url)[\d\w\s(),])*$/],
  color: [/^((?!url)[\d\w\s(),])*$/],
  'column-count': [/^((?!url)[\d\w\s(),])*$/],
  'column-fill': [/^((?!url)[\d\w\s(),])*$/],
  'column-gap': [/^((?!url)[\d\w\s(),])*$/],
  'column-rule': [/^((?!url)[\d\w\s(),])*$/],
  'column-rule-color': [/^((?!url)[\d\w\s(),])*$/],
  'column-rule-style': [/^((?!url)[\d\w\s(),])*$/],
  'column-rule-width': [/^((?!url)[\d\w\s(),])*$/],
  'column-span': [/^((?!url)[\d\w\s(),])*$/],
  'column-width': [/^((?!url)[\d\w\s(),])*$/],
  columns: [/^((?!url)[\d\w\s(),])*$/],
  // content: [/^((?!url)[\d\w\s(),])*$/],
  // 'counter-increment': [/^((?!url)[\d\w\s(),])*$/],
  // 'counter-reset': [/^((?!url)[\d\w\s(),])*$/],
  cursor: [/^((?!url)[\d\w\s(),])*$/],
  direction: [/^((?!url)[\d\w\s(),])*$/],
  // display: [/^((?!url)[\d\w\s(),])*$/],
  'empty-cells': [/^((?!url)[\d\w\s(),])*$/],
  flex: [/^((?!url)[\d\w\s(),])*$/],
  'flex-basis': [/^((?!url)[\d\w\s(),])*$/],
  'flex-direction': [/^((?!url)[\d\w\s(),])*$/],
  'flex-flow': [/^((?!url)[\d\w\s(),])*$/],
  'flex-grow': [/^((?!url)[\d\w\s(),])*$/],
  'flex-shrink': [/^((?!url)[\d\w\s(),])*$/],
  'flex-wrap': [/^((?!url)[\d\w\s(),])*$/],
  float: [/^((?!url)[\d\w\s(),])*$/],
  font: [/^((?!url)[\d\w\s(),])*$/],
  'font-family': [/^((?!url)[\d\w\s(),])*$/],
  'font-size': [/^((?!url)[\d\w\s(),])*$/],
  'font-size-adjust': [/^((?!url)[\d\w\s(),])*$/],
  'font-stretch': [/^((?!url)[\d\w\s(),])*$/],
  'font-style': [/^((?!url)[\d\w\s(),])*$/],
  'font-variant': [/^((?!url)[\d\w\s(),])*$/],
  'font-weight': [/^((?!url)[\d\w\s(),])*$/],
  height: [/^((?!url)[\d\w\s(),])*$/],
  'justify-content': [/^((?!url)[\d\w\s(),])*$/],
  left: [/^((?!url)[\d\w\s(),])*$/],
  'letter-spacing': [/^((?!url)[\d\w\s(),])*$/],
  'line-height': [/^((?!url)[\d\w\s(),])*$/],
  'list-style': [/^((?!url)[\d\w\s(),])*$/],
  'list-style-image': [/^((?!url)[\d\w\s(),])*$/],
  'list-style-position': [/^((?!url)[\d\w\s(),])*$/],
  'list-style-type': [/^((?!url)[\d\w\s(),])*$/],
  margin: [/^((?!url)[\d\w\s(),])*$/],
  'margin-bottom': [/^((?!url)[\d\w\s(),])*$/],
  'margin-left': [/^((?!url)[\d\w\s(),])*$/],
  'margin-right': [/^((?!url)[\d\w\s(),])*$/],
  'margin-top': [/^((?!url)[\d\w\s(),])*$/],
  'max-height': [/^((?!url)[\d\w\s(),])*$/],
  'max-width': [/^((?!url)[\d\w\s(),])*$/],
  'min-height': [/^((?!url)[\d\w\s(),])*$/],
  'min-width': [/^((?!url)[\d\w\s(),])*$/],
  opacity: [/^((?!url)[\d\w\s(),])*$/],
  order: [/^((?!url)[\d\w\s(),])*$/],
  outline: [/^((?!url)[\d\w\s(),])*$/],
  'outline-color': [/^((?!url)[\d\w\s(),])*$/],
  'outline-offset': [/^((?!url)[\d\w\s(),])*$/],
  'outline-style': [/^((?!url)[\d\w\s(),])*$/],
  'outline-width': [/^((?!url)[\d\w\s(),])*$/],
  overflow: [/^((?!url)[\d\w\s(),])*$/],
  'overflow-x': [/^((?!url)[\d\w\s(),])*$/],
  'overflow-y': [/^((?!url)[\d\w\s(),])*$/],
  padding: [/^((?!url)[\d\w\s(),])*$/],
  'padding-bottom': [/^((?!url)[\d\w\s(),])*$/],
  'padding-left': [/^((?!url)[\d\w\s(),])*$/],
  'padding-right': [/^((?!url)[\d\w\s(),])*$/],
  'padding-top': [/^((?!url)[\d\w\s(),])*$/],
  'page-break-after': [/^((?!url)[\d\w\s(),])*$/],
  'page-break-before': [/^((?!url)[\d\w\s(),])*$/],
  'page-break-inside': [/^((?!url)[\d\w\s(),])*$/],
  perspective: [/^((?!url)[\d\w\s(),])*$/],
  'perspective-origin': [/^((?!url)[\d\w\s(),])*$/],
  position: [/^((?!url)[\d\w\s(),])*$/],
  quotes: [/^((?!url)[\d\w\s(),])*$/],
  // resize: [/^((?!url)[\d\w\s(),])*$/],
  right: [/^((?!url)[\d\w\s(),])*$/],
  'tab-size': [/^((?!url)[\d\w\s(),])*$/],
  'table-layout': [/^((?!url)[\d\w\s(),])*$/],
  'text-align': [/^((?!url)[\d\w\s(),])*$/],
  'text-align-last': [/^((?!url)[\d\w\s(),])*$/],
  'text-decoration': [/^((?!url)[\d\w\s(),])*$/],
  'text-decoration-color': [/^((?!url)[\d\w\s(),])*$/],
  'text-decoration-line': [/^((?!url)[\d\w\s(),])*$/],
  'text-decoration-style': [/^((?!url)[\d\w\s(),])*$/],
  'text-indent': [/^((?!url)[\d\w\s(),])*$/],
  'text-justify': [/^((?!url)[\d\w\s(),])*$/],
  'text-overflow': [/^((?!url)[\d\w\s(),])*$/],
  'text-shadow': [/^((?!url)[\d\w\s(),])*$/],
  'text-transform': [/^((?!url)[\d\w\s(),])*$/],
  top: [/^((?!url)[\d\w\s(),])*$/],
  // transform: [/^((?!url)[\d\w\s(),])*$/],
  // 'transform-origin': [/^((?!url)[\d\w\s(),])*$/],
  // 'transform-style': [/^((?!url)[\d\w\s(),])*$/],
  // transition: [/^((?!url)[\d\w\s(),])*$/],
  // 'transition-delay': [/^((?!url)[\d\w\s(),])*$/],
  // 'transition-duration': [/^((?!url)[\d\w\s(),])*$/],
  // 'transition-property': [/^((?!url)[\d\w\s(),])*$/],
  // 'transition-timing-function': [/^((?!url)[\d\w\s(),])*$/],
  'vertical-align': [/^((?!url)[\d\w\s(),])*$/],
  visibility: [/^((?!url)[\d\w\s(),])*$/],
  'white-space': [/^((?!url)[\d\w\s(),])*$/],
  // width: [/^((?!url)[\d\w\s(),])*$/],
  'word-break': [/^((?!url)[\d\w\s(),])*$/],
  'word-spacing': [/^((?!url)[\d\w\s(),])*$/],
  'word-wrap': [/^((?!url)[\d\w\s(),])*$/],
  'z-index': [/^(-)?(\d{1, 3})$/], // only allow z-index from -999 to 999
};

export default allowedStyles;
